name: Build Images

on:
  push:


jobs:
  build:
    name: Build Docker Images and Save as Artifacts
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Retrieve the short Git commit SHA
      - name: Get Short Git SHA
        id: get_sha
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        shell: bash
